# Classes exercises configuration
---
classs:
  - exercises:
      - file: "../1.md"
        title: "Exercise #1"
      - file: "../2.md"
        title: "Exercise #2"
      - file: "../3.rst"
        title: "Exercise #3"
